---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(janitor)

heart_disease_data_scotland <- read_csv("raw_data/cvd_mortality_scotland.csv")
```

```{r}
# clean_names(heart_disease_data_scotland)
# 
# glimpse(heart_disease_data_scotland)
# 
# heart_disease_data_scotland %>% 
#   group_by(Diagnosis) %>% 
#   count()
```

```{r}
# heart_disease_data_scotland %>% 
#   group_by(HBR) %>% 
#   count()
```

```{r}
#Cleaning Script
heart_disease_scotland_clean <- heart_disease_data_scotland %>%
  clean_names() %>%
  select(-crude_rate_qf, -number_of_deaths_qf, -sex_qf, -age_group_qf,
         -hbrqf) %>%
  mutate(hbr = ifelse(hbr == "S08000015", "Ayrshire and Arran", hbr),
         hbr = ifelse(hbr == "S08000016", "Borders", hbr),
         hbr = ifelse(hbr == "S08000017", "Dumfries and Galloway", hbr),
         hbr = ifelse(hbr == "S08000018", "Fife", hbr),
         hbr = ifelse(hbr == "S08000019", "Forth Valley", hbr),
         hbr = ifelse(hbr == "S08000020", "Grampian", hbr),
         hbr = ifelse(hbr == "S08000021", "Greater Glasgow and Clyde", hbr),
         hbr = ifelse(hbr == "S08000022", "Highland", hbr),
         hbr = ifelse(hbr == "S08000023", "Lanarkshire", hbr),
         hbr = ifelse(hbr == "S08000024", "Lothian", hbr),
         hbr = ifelse(hbr == "S08000025", "Orkney", hbr),
         hbr = ifelse(hbr == "S08000026", "Shetland", hbr),
         hbr = ifelse(hbr == "S08000027", "Tayside", hbr),
         hbr = ifelse(hbr == "S08000028", "Western Isles", hbr),
         hbr = ifelse(hbr == "S08000029", "Fife", hbr),
         hbr = ifelse(hbr == "S08000030", "Tayside", hbr),
         hbr = ifelse(hbr == "S08000031", "Greater Glasgow and Clyde", hbr),
         hbr = ifelse(hbr == "S08000032", "Lanarkshire", hbr),
         hbr = ifelse(hbr == "S92000003", "All of Scotland", hbr)
         ) %>%
  rename(age_group_years = age_group,
         nhs_health_board = hbr) %>%
  mutate(age_group_years = str_remove(age_group_years, " years"),
         sex = str_remove(sex, "[s]"))
# 
# write_csv(heart_disease_scotland_clean, "clean_data/clean_heart_disease_scotland.csv")

```
 
```{r}
#admissions and discharges graph by healthboard
heart_disease_scotland_clean %>% 
  filter(nhs_health_board == "Fife") %>% 
  group_by(admission_type) %>% 
  summarise(total_num_discharges = sum(number_of_discharges)) %>% 
  ggplot() +
  aes(x = admission_type, y = total_num_discharges) +
  geom_col()
  
```

```{r}
#diagnosis and discharges graph by healthboard and sex (removed all diangoses)

heart_disease_scotland_clean %>% 
  filter(nhs_health_board %in% "Borders", 
         sex %in% "Male",
         admission_type != "All") %>%
  ggplot() +
  aes(x = diagnosis, y = number_of_discharges, fill = admission_type) +
  geom_col()
```

```{r}
#crude rate by health board, filter by financial year, age group and sex
heart_disease_scotland_clean %>% 
  filter(year %in% "2012",
         age_group_years %in% "0-44",
         sex %in% "Female") %>%
  ggplot() +
  aes(x = nhs_health_board, y = crude_rate, fill = sex) +
  geom_col(show.legend = FALSE) +
  coord_flip()
  
```

```{r}
  # output$crude_rate_graph <- renderPlot({
  #   heart_disease_scotland %>% 
  #     filter(financial_year %in% input$year_input,
  #            age_group_years %in% input$age_input,
  #            sex %in% input$sex_input) %>%
  #     ggplot() +
  #     aes(x = nhs_health_board, y = crude_rate) +
  #     geom_col() +
  #     coord_flip()
```

```{r}

heart_disease_scotland_clean %>% 
  filter(nhs_health_board %in% "All of Scotland",
        age_group_years %in% "0-44", 
        sex %in% "Male") %>%
  ggplot() +
  aes(x = year, y = number_of_deaths) +
  geom_col() +
  scale_x_discrete()


```

