---
title: "R Notebook"
output: html_notebook
---

# MVP

## 1

```{r}
library(tidyverse)
housing_prices <- read_csv("data/housing_prices.csv")
library(mosaic)
library(mosaicData)
library(janitor)
library(tidyverse)
library(GGally)
library(ggfortify)

housing_prices
summary(housing_prices)

glimpse(housing_prices)
housing_prices %>% 
  distinct(ocean_proximity)
```
# 2

```{r message=FALSE, warning=FALSE}
housing_prices %>% 
  ggpairs(progress = FALSE)


```

The ggpairs plot although difficult to read suggests a strong relationship between the total number of bedrooms and total number of rooms (see linear scatter plot on ggpairs plot and high correlation coeff of 0.934)

# 3

```{r}
# dropped total_bedrooms column
housing_prices_trim <- housing_prices %>% 
  select(-total_bedrooms)
```

# 4
i)
```{r}
housing_prices_trim %>% 
  ggpairs(progress = FALSE)

```
 
 
ii)
median_house_value ~ median_income


```{r}

housing_prices_trim %>% 
  ggplot() +
  aes(x = median_house_value, y = median_income) +
  geom_point() +
  geom_smooth(method ="lm")

```
median_house_value ~ total_rooms

```{r}
housing_prices_trim %>% 
  ggplot() +
  aes(x = median_house_value, y = total_rooms) +
  geom_point() +
  geom_smooth(method ="lm")
```
median_house_value ~ households
```{r}
housing_prices_trim %>% 
  ggplot() +
  aes(x = median_house_value, y = households) +
  geom_point() +
  geom_smooth(method ="lm")

```
 
```{r}
library(fastDummies)

housing_prices_dummy <- housing_prices_trim %>% 
  fastDummies::dummy_cols(select_columns = "ocean_proximity",
                          remove_first_dummy =  TRUE,
                          remove_selected_columns = TRUE)

# you should expect to get 4 dummy variables as dummy variables = number of variables - 1
```
 
#6.

```{r}

model1 <- lm(median_house_value ~ median_income, data = housing_prices_trim)

```

```{r}

autoplot(model1)

summary(model1)

```

# 7

```{r}

model2 <- lm(median_house_value ~ median_income + housing_median_age, data = housing_prices_trim)

autoplot(model2)
# graph1: the data does not deviate too far from 0 so suggests that the residuals are independent.
# graph 2: the data is relatively normal distributed except for at the tails
# graph 3: the data looks to be in a band (kind of) above 0 so there is more or less constant variation in the data.
# summary p -values should be reliable

summary(model2)

# both predictors are significant (***)
# This means that median_house_value is affected significantly by both median_income and housing_median_age

```


