---
title: "R Notebook"
output: html_notebook
---

```{r}
#libraries and data
library(tidyverse)
library(broom)
library(janitor)
library(factoextra)
library(GGally)
library(ggforce)
library(ggrepel)

mall_customers <- read_csv("data/mall_customers.csv")
```
## Task 1
```{r}

mall_customers <- mall_customers %>% 
  clean_names() %>% 
  select(-customer_id)

mall_customers %>% 
  ggpairs(progress = FALSE)

# Comments: according to ggpairs there are no strong correlations between variables,
# there is a weak correlation between age and spending score and age. we can see
  

```

```{r}
mall_customers %>% 
  count(gender)
# more females than males in the data

summary(mall_customers)
# age range 18-70
# annual income range = 15-137k
# spending_score range 1-99
```
## Task 2

```{r}
mall_customers %>% 
  ggplot() +
  aes(x = spending_score_1_100, y = annual_income_k) +
  geom_point()
# from examining data its looks like there could be 5 clusters 
```

```{r}
# set the scale and removed age and gender columns

scale_mall_customers <- mall_customers %>% 
  select(annual_income_k, spending_score_1_100) %>% 
  mutate(across(everything(),
                .fns = scale))

```

```{r}
# kmeans clustering, elbow method

min_k <- 1
max_k <- 20

k_clusters <- tibble(k = min_k:max_k) %>% 
  mutate(kclust = map(k, ~ kmeans(scale_mall_customers, centers = .x, nstart = 25)),
         tidied = map(kclust, tidy),
         glanced = map(kclust, glance),
         augmented = map(kclust, augment, scale_mall_customers))

clusterings <- k_clusters %>% 
  unnest(glanced)

clusterings %>% 
  ggplot(aes(x = k,
             y=tot.withinss)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = seq(1, 20, 1))

# from visual examination 5, 6 or 7 look like a good number of clusters.
```
```{r}
# silhouette method

fviz_nbclust(scale_mall_customers,
             kmeans,
             method = "silhouette",
             nstart = 25)

# using the silhouette method 5 is also the suggested number of clusters.
```
```{r}
# and gap stat method 
fviz_nbclust(scale_mall_customers,
             kmeans,
             method ="gap_stat",
             nstart = 25)
# gap stat suggests only one cluster. will go with intuition and silhouette method.
```

## Task 3
```{r}
# visualisation of clustering
# 5 clusters

clusterings %>% 
  unnest(augmented) %>% 
  filter(k ==5) %>% 
  ggplot(aes(x =annual_income_k, y =spending_score_1_100,
             colour = .cluster)) +
  geom_point() +
  theme_bw() +
  scale_colour_brewer(palette= "Dark2")

# 5 clusters looks good to me

```
## Task 4:

Clustering using a k of 5 seems a good fit for this data as we can clearly see clusters which appear similar.

## Task 5:

```{r}
clusterings %>% 
  unnest(augmented) %>% 
  filter(k ==5) %>% 
  ggplot(aes(x =annual_income_k, y =spending_score_1_100,
             colour = .cluster)) +
  geom_point() +
  theme_bw() +
  scale_colour_brewer(palette= "Dark2") +
  geom_mark_ellipse(aes(fill = as.factor(.cluster)), expand = unit(0.5,"mm")) +
  theme(legend.position = "none")

#sorry I'm colourblind so apologies if the colour labels aren't accurate
# green = low income, big spenders
# red = high income, big spenders,
# orange/yellow = low income, small spenders
# purple = high income, small spenders
# blue = mid income, mid spenders
```

